aliases = {
    '"Dum-Dum" Dugan': "Corporal Dum Dum Dugan",
    'Bertram "Binky" Biggs': "Binky Biggs",
    'General Thaddeus "Thunderbolt" Ross': "General Thunderbolt Ross",
    'Hellcat [Patricia "Patsy" Walker]': "Hellcat [Patsy Walker]",
    'Hellcat [Patricia "Patsy" Walker]': "Hellcat [Patsy Walker]",
    'Kyle "Ace" Morgan': "Ace Morgan",
    'Leslie "Rocky" Davis': "Rocky Davis",
    'Matthew "Red" Ryan': "Red Ryan",
    'Old Man Logan [James "Logan" Howlett]': "Old Man Logan [James Howlett]",
    'Psylocke [Elizabeth "Betsy" Braddock]': "Psylocke [Elizabeth Braddock]",
    'Thaddeus "Thunderbolt" Ross': "General Thunderbolt Ross",
    'Walter Mark "Prof" Haley': "Professor Haley",
    'Wolverine [James "Logan" Howlett]': "Wolverine [Logan/ James Howlett]",
    " Beast": "Beast [Hank McCoy]",
    """Plastic Man [Patrick "Eel" O'Brian]""": "Plastic Man [Eel O'Brian]",
    """Winter Soldier [James Buchanan "Bucky" Barnes]""": "Winter Soldier [Bucky Barnes]",
    "[Power Man] Luke Cage": "Power Man [Luke Cage]",
    "A.R.G.U.S. [Colonel Steve Trevor]": "Steve Trevor",
    "A.R.G.U.S. [Steve Trevor]": "Steve Trevor",
    "Abomination [Emil Blonsky]": "Abomination [Emil Blonski]",
    "Abraham Sapien": "Abe Sapien",
    "Absorbing Man": "Absorbing Man [Crusher Creel]",
    "Adolph Hitler": "Adolf Hitler",
    "Agent Venom [Flash Thompson]": "Venom [Flash Thompson]",
    "Alex Power": "Gee [Alex Power]",
    "Alex Summers [Havok]": "Havok [Alex Summers]",
    "Amora the Enchantress": "Enchantress [Amora]",
    "Anakin Skywalker [Dark Vader]": "Darth Vader [Anakin Skywalker]",
    "Anakin Skywalker [Darth Vader]": "Darth Vader [Anakin Skywalker]",
    "Angel [Warren Worthington]": "Angel [Warren Worthington III]",
    "Angel": "Angel [Warren Worthington III]",
    "Animal Man": "Animal Man [Buddy Baker]",
    "Animal-Man": "Animal Man [Buddy Baker]",
    "Ant Man": "Ant Man [Hank Pym]",
    "Ant-Man [Hank Pym]": "Ant Man [Hank Pym]",
    "Ant-Man [Henry Pym]": "Ant Man [Hank Pym]",
    "Ant-Man": "Ant Man [Hank Pym]",
    "Apocalypse": "Apocalypse [En Sabah Nur]",
    "Apollo": "Apollo [Andrew]",
    "Aqualad [Kaldur]": "Aqualad [Kaldur'Ahm]",
    "Aqualad": "Aqualad [Jackson Hyde]",
    "Aquaman (of Earth-1)": "Aquaman [Arthur Curry]",
    "Aquaman": "Aquaman [Arthur Curry]",
    "Archangel": "Archangel [Warren Worthington III]",
    "Armor": "Armor [Hisako Ichiki]",
    "Arsenal": "Arsenal [Roy Harper]",
    "Artemis": "Artemis [Artemis Crock]",
    "Atom [Al Pratt]": "The Atom [Al Pratt]",
    "Atom Smasher [Albert Rothstein]": "Atom Smasher [Al Rothstein]",
    "Atom Smasher": "Atom Smasher [Al Rothstein]",
    "Atom-Smasher [Al Rothstein]": "Atom Smasher [Al Rothstein]",
    "Atom-Smasher": "Atom Smasher [Al Rothstein]",
    "Atom": "Atom [Ray Palmer]",
    "Aurora": "Aurora [Jeanne-Marie Beaubier]",
    "Azrael [Jean-Paul Valley]": "Azrael [Jean Paul Valley]",
    "Azrael [Jean-Pual Valley]": "Azrael [Jean Paul Valley]",
    "Azrael [Ludovic Valley]": "Azrael [Jean Paul Valley]",
    "Azrael [Michael Lane]": "Azrael [Jean Paul Valley]",
    "Azrael": "Azrael [Jean Paul Valley]",
    "Baman [Bruce Wayne]": "Batman [Bruce Wayne]",
    "Banshee": "Banshee [Theresa Rourke Cassidy]",
    "Barbara Gordon [Batgirl]": "Batgirl [Barbara Gordon]",
    "Barbara Gordon [Oracle]": "Oracle [Barbara Gordon]",
    "Barda": "Big Barda",
    "Barry Allen [Flash]": "Flash [Barry Allen]",
    "Batgirl [Barbara Gordan]": "Batgirl [Barbara Gordon]",
    "Batgirl [Barbara Gourdon]": "Batgirl [Barbara Gordon]",
    "Batgirl [Stephanie Brown/ also as Spoiler]": "Batgirl [Stephanie Brown]",
    "Batgirl": "Batgirl [Barbara Gordon]",
    "Batman ": "Batman [Bruce Wayne]",
    "Batman (Earth-1)": "Batman [Bruce Wayne]",
    "Batman (Earth-2)": "Batman [Bruce Wayne]",
    "Batman (of Earth-1)": "Batman [Bruce Wayne]",
    "Batman (of Earth-2)": "Batman [Bruce Wayne]",
    "Batman [Bruce Wayne] (Earth One)": "Batman [Bruce Wayne]",
    "Batman [Bruce Wayne] (Earth-1)": "Batman [Bruce Wayne]",
    "Batman [Bruce Wayne] (Earth-2)": "Batman [Bruce Wayne]",
    "Batman [Dick Grayson]": "Batman [Bruce Wayne]",
    "Batman [Jean Paul Valley]": "Batman [Jean-Paul Valley]",
    "Batman": "Batman [Bruce Wayne]",
    "Batwoman [Katherine Kane]": "Batwoman [Kate Kane]",
    "Batwoman [Kathy Kane]": "Batwoman [Kate Kane]",
    "Batwoman": "Batwoman [Kate Kane]",
    "Beast (1964)": "Beast [Hank McCoy]",
    "Beast [Henry McCoy]": "Beast [Hank McCoy]",
    "Beast Boy [Garfied Logan]": "Beast Boy [Gar Logan]",
    "Beast Boy [Garfield Logan]": "Beast Boy [Gar Logan]",
    "Beast Boy": "Beast Boy [Gar Logan]",
    "Beast": "Beast [Hank McCoy]",
    "Beetle": "Beetle [Abner Jenkins]",
    "Ben Grimm [The Thing]": "The Thing [Ben Grimm]",
    "Ben Grimm [the Thing]": "The Thing [Ben Grimm]",
    "Ben Grimm": "The Thing [Ben Grimm]",
    "Ben Turner [Bronze Tiger]": "Bronze Tiger [Ben Turner]",
    "Betsy Braddock [Psylocke]": "Psylocke [Elizabeth Braddock]",
    "Betsy Braddock": "Psylocke [Elizabeth Braddock]",
    "Big Ethel Muggs": "Ethel Muggs",
    "Bishop": "Bishop [Lucas Bishop]",
    "Black Adam": "Black Adam [Teth-Adam]",
    "Black Bolt [Blackagar]": "Black Bolt [Blackagar Boltagon]",
    "Black Bolt": "Black Bolt [Blackagar Boltagon]",
    "Black Canary (Earth-2)": "Black Canary [Dinah Laurel Lance]",
    "Black Canary [Dinah Drake Lance]": "Black Canary [Dinah Laurel Lance]",
    "Black Canary [Dinah Drake]": "Black Canary [Dinah Laurel Lance]",
    "Black Canary [Dinah Lance]": "Black Canary [Dinah Laurel Lance]",
    "Black Canary [Dinah Laurel Lance Queen]": "Black Canary [Dinah Laurel Lance]",
    "Black Canary": "Black Canary [Dinah Laurel Lance]",
    "Black Cat [Felicia Hardy]": "Black Cat",
    "Black Knight": "Black Knight [Dane Whitman]",
    "Black Lightning": "Black Lightning [Jefferson Pierce]",
    "Black Panther (T'Challa)": "Black Panther [T'Challa]",
    "Black Panther [T'challa]": "Black Panther [T'Challa]",
    "Black Panther": "Black Panther [T'Challa]",
    "Black Widow [Natalia Romanova]": "Black Widow [Natasha Romanov]",
    "Black Widow [Natasha Romanoc]": "Black Widow [Natasha Romanov]",
    "Black Widow [Natasha Romanoff]": "Black Widow [Natasha Romanov]",
    "Black Widow [Natasha Romanova]": "Black Widow [Natasha Romanov]",
    "Black Widow [Natasha Romanova/ also as Nancy Rushman]": "Black Widow [Natasha Romanov]",
    "Black Widow": "Black Widow [Natasha Romanov]",
    "Blackhawk [Janos Prohaska]": "Blackhawk",
    "Blade": "Blade [Eric Brooks]",
    "Blob [Fred Dukes]": "Blob [Fred J. Dukes]",
    "Blob": "Blob [Fred J. Dukes]",
    "Bloodshot [Angelo Mortalli": "Bloodshot [Angelo Mortalli]",
    "Bloodshot": "Bloodshot [Angelo Mortalli]",
    "Blue Beetle [Jamie Reyes]": "Beetle [Abner Jenkins]",
    "Blue Beetle [Ted Kord]": "Blue Beetle [Jaime Reyes]",
    "Blue Beetle": "Blue Beetle [Jaime Reyes]",
    "Blue Devil [Daniel Cassidy]": "Blue Devil [Dan Cassidy]",
    "Blue Devil": "Blue Devil [Dan Cassidy]",
    "Bobbi Morse [Mockingbird]": "Mockingbird [Bobbi Morse]",
    "Bobby Drake [Iceman]": "Iceman [Bobby Drake]",
    "Boom Boom": "Boom-Boom [Tabitha Smith]",
    "Boom-Boom": "Boom-Boom [Tabitha Smith]",
    "Boomerang": "Boomerang [Fred Myers]",
    "Booster Gold [Michael Carter]": "Booster Gold [Michael Jon Carter]",
    "Booster Gold [Micheal Jon Carte]": "Booster Gold [Michael Jon Carter]",
    "Booster Gold": "Booster Gold [Michael Jon Carter]",
    "Bouncing Boy": "Bouncing Boy [Chuck Taine]",
    "Brainiac 5": "Brainiac 5 [Querl Dox]",
    "Britanic [Brian Braddock]": "Captain Britain [Brian Braddock]",
    "Britanic": "Captain Britain [Brian Braddock]",
    "Bronze Tiger": "Bronze Tiger [Ben Turner]",
    "Bruce Banner [Hulk]": "Hulk [Bruce Banner]",
    "Bruce Wayne [Batman]": "Batman [Bruce Wayne]",
    "Bucky [Bucky Barnes]": "Bucky [James Buchanan Barnes]",
    "Bucky [James Barnes]": "Bucky [James Buchanan Barnes]",
    "Bucky Barnes": "Bucky [James Buchanan Barnes]",
    "Bucky": "Bucky [James Buchanan Barnes]",
    "Bumblebee [Karen Beecher]": "Bumblebee [Karen Beecher-Duncan]",
    "Bumblebee": "Bumblebee [Karen Beecher-Duncan]",
    "Bunker": "Bunker [Miguel Jose Barragan]",
    "Cable [Mathan Summers]": "Cable [Nathan Summers]",
    "Cable [Nathaniel Summers]": "Cable [Nathan Summers]",
    "Cable": "Cable [Nathan Summers]",
    "Cannonball": "Cannonball [Sam Guthrie]",
    "Captain  America [Steve Rogers]": "Captain America [Steve Rogers]",
    "Captain America [Barnes]": "Captain America [Bucky Barnes]",
    "Captain America [James Buchanan Barnes]": "Captain America [Bucky Barnes]",
    "Captain America": "Captain America [Steve Rogers]",
    "Captain Atom": "Captain Atom [Nathaniel Adam]",
    "Captain Boomerang [Digger Harkness]": 'Captain Boomerang [George "Digger" Harkness]',
    "Captain Boomerang [George Harkness]": 'Captain Boomerang [George "Digger" Harkness]',
    "Captain Boomerang [George Harkness/ also as Digger]": 'Captain Boomerang [George "Digger" Harkness]',
    "Captain Boomerang [Owen Harkness]": "Captain Boomerang, Jr. [Owen Mercer]",
    "Captain Boomerang [Owen Hawkness]": "Captain Boomerang, Jr. [Owen Mercer]",
    "Captain Boomerang [Owen Mercer]": "Captain Boomerang, Jr. [Owen Mercer]",
    "Captain Boomerang": 'Captain Boomerang [George "Digger" Harkness]',
    "Captain Britain": "Captain Britain [Brian Braddock]",
    "Captain Cold": "Captain Cold [Leonard Snart]",
    "Captain Comet [Adam Blake]": "Comet [Adam Blake]",
    "Captain Comet": "Comet [Adam Blake]",
    "Captain Marvel (Mar-Vell)": "Captain Marvel [Mar-Vell]",
    "Captain Marvel Jr.": "Captain Marvel, Jr. [Freddy Freeman]",
    "Captain Marvel Junior.": "Captain Marvel, Jr. [Freddy Freeman]",
    "Captain Marvel, Jr.": "Captain Marvel, Jr. [Freddy Freeman]",
    "Captain Marvel": "Captain Marvel [Mar-Vell]",
    "Carnage": "Carnage [Cletus Kasady]",
    "Catwoman [Selina Kyle-Wayne] (Earth-2)": "Catwoman [Selina Kyle]",
    "Catwoman [Selina Kyle/ also as Irena Dubrovna]": "Catwoman [Selina Kyle]",
    "Catwoman [Selina Kyle/ as Cat-Woman]": "Catwoman [Selina Kyle]",
    "Catwoman": "Catwoman [Selina Kyle]",
    "Chamber": "Jono [Chamber]",
    "Chameleon Boy": "Chameleon Boy [Reep Daggle]",
    "Chameleon": "Chameleon Boy [Reep Daggle]",
    "Changeling [Gar Logan]": "Changeling [Garfield Logan]",
    "Changeling": "Changeling [Garfield Logan]",
    "Charles Xavier": "Professor X [Charles Xavier]",
    "Clark Kent [Superboy]": "Superboy [Kal-El/ Clark Kent]",
    "Clark Kent [Superman]": "Superman [Clark Kent/ Kal-El]",
    "Clark Kent [Superman/ Kal-El]": "Superman [Clark Kent/ Kal-El]",
    "Clayface [Baskil Karlo]": "Clayface [Basil Karlo]",
    "Clayface [Ethan Bennett]": "Clayface [Basil Karlo]",
    "Clayface [Matt Hagen]": "Clayface [Basil Karlo]",
    "Clayface [Matthew Hagen]": "Clayface [Basil Karlo]",
    "Clayface [Preston Payne]": "Clayface [Basil Karlo]",
    "Clayface": "Clayface [Basil Karlo]",
    "Clint Barton [Hawkeye]": "Hawkeye [Clint Barton]",
    "Cloak [Ty Johnson]": "Cloak [Tyrone Johnson]",
    "Cloak": "Cloak [Tyrone Johnson]",
    "Col. Nick Fury": "Nick Fury",
    "Col. Steve Trevor": "Steve Trevor",
    "Colonel Nick Fury": "Nick Fury",
    "Colonel Steve Trevor": "Steve Trevor",
    "Colossal Boy": "Colossal Boy [Gim Allon]",
    "Colossus [Peter Rasputin]": "Colossus [Piotr Rasputin]",
    "Colossus": "Colossus [Piotr Rasputin]",
    "Comet": "Comet [Adam Blake]",
    "Commissioner Gordon": "Commissioner James Gordon",
    "Cosmic Boy": "Cosmic Boy [Rokk Krinn]",
    "Cosmic Ghost Rider": "Cosmic Ghost Rider [Frank Castle]",
    "Cosmic Ghost Rider": "Cosmic Ghost Rider [Frank Castle]",
    "Count Vertigo": "Count Vertigo [Werner Vertigo]",
    "Crystal [Crystalia Maximoff]": "Crystal [Crystalia Amaquelin]",
    "Crystal": "Crystal [Crystalia Amaquelin]",
    "Curt Connors [Lizard]": "Lizard [Curt Connors]",
    "Cyborg [Vic Stone]": "Cyborg [Victor Stone]",
    "Cyborg Superman": "Cyborg Superman [Hank Henshaw]",
    "Cyborg-Superman [Hank Henshaw]": "Cyborg Superman [Hank Henshaw]",
    "Cyborg": "Cyborg [Victor Stone]",
    "Cyclops": "Cyclops [Scott Summers]",
    "Daffy Duck [as Duck Dodgers]": "Daffy Duck",
    "Daffy Duck [As Duck Dodgers]": "Daffy Duck",
    "Daffy Duck [as Duck Quackahan]": "Daffy Duck",
    "Daffy Duck [as Robin Hood]": "Daffy Duck",
    "Daffy Duck [Duck Dodgers]": "Daffy Duck",
    "Daffy Duck [Stupor-Duck][Duck Dent]": "Daffy Duck",
    "Dagger": "Dagger [Tandy Bowen]",
    "Daimon Hellstrom": "Son of Satan [Daimon Hellstrom]",
    "Daken": "Wolverine [Daken]",
    "Damian Wayne [Robin]": "Robin [Damian Wayne]",
    "Dani Moonstar": "Mirage [Dani Moonstar]",
    "Daredevil": "Daredevil [Matt Murdock]",
    "Darkhawk": "Darkhawk [Chris Powell]",
    "Dart Vader": "Darth Vader [Anakin Skywalker]",
    "Darth Vader [Anakin Sywalker]": "Darth Vader [Anakin Skywalker]",
    "Darth Vader": "Darth Vader [Anakin Skywalker]",
    "Dazzler [Allison Blaire]": "Dazzler [Alison Blaire]",
    "Dazzler": "Dazzler [Alison Blaire]",
    "Deadman": "Deadman [Boston Brand]",
    "Deadpool": "Deadpool [Wade Wilson]",
    "Deadshot": "Deadshot [Floyd Lawton]",
    "Death's Head 3.0": "Death's Head II",
    "Death's Head": "Death's Head II",
    "Deathlok [Henry Hayes]": "Deathlok [Luther Manning]",
    "Deathlok [Michael Collins]": "Deathlok [Luther Manning]",
    "Deathlok": "Deathlok [Luther Manning]",
    "Deathstroke the Terminator [Slade Wilson]": "Deathstroke [Slade Wilson]",
    "Deathstroke the Terminator": "Deathstroke [Slade Wilson]",
    "Deathstroke": "Deathstroke [Slade Wilson]",
    "Demon [Etrigan]": "Demon [Etrigan/ Jason Blood]",
    "Destroyer": "Destroyer [Alex Power]",
    "Detective Jim Corrigan [Spectre]": "Spectre [Jim Corrigan]",
    "Diana [Wonder Woman]": "Wonder Woman [Diana Prince]",
    "Dick Grayson [Nightwing]": "Nightwing [Dick Grayson]",
    "Dinah Lance [Black Canary]": "Black Canary [Dinah Laurel Lance]",
    "Doc Savage [Clark Savage Jr]": "Doc Savage [Clark Savage Jr.]",
    "Doc Savage": "Doc Savage [Clark Savage Jr.]",
    "Doctor Aphra": "Doctor Aphra [Chelli Lona Aphra]",
    "Doctor Doom [2099]": "Doom of 2099",
    "Doctor Doom [Victor Von Doom]": "Doctor Doom [Victor von Doom]",
    "Doctor Doom": "Doctor Doom [Victor von Doom]",
    "Doctor Fate [Hector Hall]": "Dr. Fate [Kent Nelson]",
    "Doctor Fate [Kent Nelson]": "Dr. Fate [Kent Nelson]",
    "Doctor Fate [Kent V. Nelson]": "Dr. Fate [Kent Nelson]",
    "Doctor Fate": "Dr. Fate [Kent Nelson]",
    "Doctor Mid-Nite [Pieter Cross]": "Doctor Mid-Nite [Charles McNider]",
    "Doctor Mid-Nite": "Doctor Mid-Nite [Charles McNider]",
    "Doctor Octopus [Otto Octavius]": "Doctor Octopus",
    "Doctor Polaris": "Dr. Polaris",
    "Doctor Spectrum": "Doctor Spectrum [Joseph Ledger]",
    "Doctor Stephen Strange": "Doctor Strange [Stephen Strange]",
    "Doctor Strange [Stephan Strange]": "Doctor Strange [Stephen Strange]",
    "Doctor Strange": "Doctor Strange [Stephen Strange]",
    "Doctor Voodoo": "Doctor Voodoo [Jericho Drumm]",
    "Doctor": "The Doctor",
    "Domino [Neena Thurman]": "Domino",
    "Donald Duck [as The Duck Avenger]": "Donald Duck [The Duck Avenger]",
    "Donna Troy": "Wonder Girl [Donna Troy]",
    "Doom [Victor von Doom]": "Doctor Doom [Victor von Doom]",
    "Doom 2099": "Doom of 2099",
    "Doom": "Doctor Doom [Victor von Doom]",
    "Dr Doom": "Doctor Doom [Victor von Doom]",
    "Dr Octopus": "Doctor Octopus",
    "Dr Strange": "Doctor Strange [Stephen Strange]",
    "Dr. Bruce Banner": "Bruce Banner",
    "Dr. Doom [Victor Von Doom]": "Doctor Doom [Victor von Doom]",
    "Dr. Doom [Victor von Doom]": "Doctor Doom [Victor von Doom]",
    "Dr. Doom": "Doctor Doom [Victor von Doom]",
    "Dr. Fate [Kent V. Nelson]": "Dr. Fate [Kent Nelson]",
    "Dr. Fate [Khalid Nassour]": "Doctor Fate [Khalid Nassour]",
    "Dr. Fate": "Dr. Fate [Kent Nelson]",
    "Dr. Hank Pym": "Doctor Pym [Henry Pym]",
    "Dr. Henry Pym": "Doctor Pym [Henry Pym]",
    "Dr. Mid-Nite [Dr. Charles McNider]": "Doctor Mid-Nite [Charles McNider]",
    "Dr. Mid-Nite [Pieter Cross]": "Doctor Mid-Nite [Charles McNider]",
    "Dr. Octopus [Otto Octavius]": "Doctor Octopus",
    "Dr. Octopus": "Doctor Octopus",
    "Dr. Pym": "Doctor Pym [Henry Pym]",
    "Dr. Stephen Strange": "Doctor Strange [Stephen Strange]",
    "Dr. Strange [Stephan Strange]": "Doctor Strange [Stephen Strange]",
    "Dr. Strange [Stephen Strange]": "Doctor Strange [Stephen Strange]",
    "Dr. Strange": "Doctor Strange [Stephen Strange]",
    "Drax [Arthur Douglas]": "Drax the Destroyer",
    "Drax the Destroyer [Arthur Douglas]": "Drax the Destroyer",
    "Drax, the Destroyer": "Drax the Destroyer",
    "Drax": "Drax the Destroyer",
    "Draz the Destroyer": "Drax the Destroyer",
    "Dream Girl": "Dream Girl [Nura Nal]",
    "Duck Dodgers [Daffy Duck]": "Daffy Duck",
    "Dum Dum Dugan": "Corporal Dum Dum Dugan",
    "Dum-Dum Dugan": "Corporal Dum Dum Dugan",
    "Duo Damsel": "Duo Damsel [Luornu Durgo]",
    "Elasti Girl [Rita Phar]": "Elasti-Girl [Rita Farr]",
    "Elasti Girl": "Elasti-Girl [Rita Farr]",
    "Elasti-Girl": "Elasti-Girl [Rita Farr]",
    "Elasti-Woman [Rita Farr]": "Elasti-Girl [Rita Farr]",
    "Electro [Maxwell Dillon]": "Electro [Max Dillon]",
    "Electro": "Electro [Max Dillon]",
    "Elektra Natchios": "Elektra [Elektra Natchios]",
    "Elektra": "Elektra [Elektra Natchios]",
    "Element Lad": "Element Lad [Jan Arrah]",
    "Elizabeth Braddock": "Psylocke [Elizabeth Braddock]",
    "Elongated Man": "Elongated Man [Ralph Dibny]",
    "Elongated Man": "Elongated Man [Ralph Dibny]",
    "Emma Forst [White Queen]": "Emma Frost [White Queen]",
    "Emma Frost": "Emma Frost [White Queen]",
    "Enchantress": "Enchantress [June Moone]",
    "Enchantress": "Enchantress [June Moone]",
    "Energizer": "Energizer [Katie Power]",
    "Ethel Muggs [Big Ethel]": "Ethel Muggs",
    "Etrigan the Demon": "Demon [Etrigan/ Jason Blood]",
    "Etrigan The Demon": "Demon [Etrigan/ Jason Blood]",
    "Etrigan": "Demon [Etrigan/ Jason Blood]",
    "Falcon": "Falcon [Sam Wilson]",
    "Fandrall": "Fandral",
    "Faust": "Faust [Sebastian Faust]",
    "Fire [Beatriz DaCosta]": "Fire [Beatriz da Costa]",
    "Fire [Beatriz]": "Fire [Beatriz da Costa]",
    "Fire": "Fire [Beatriz da Costa]",
    "Firebrand [Alex Sanchez]": "Firebrand [Danette Reilly]",
    "Firebrand [Gary Gilbert]": "Firebrand [Danette Reilly]",
    "Firebrand [Rick Dennison]": "Firebrand [Danette Reilly]",
    "Firebrand [Rod Reilly]": "Firebrand [Danette Reilly]",
    "Firebrand": "Firebrand [Danette Reilly]",
    "Firestar": "Firestar [Angelica Jones]",
    "Firestorm [Jason Rusch]": "Firestorm [Ronnie Raymond/ Professor Martin Stein]",
    "Firestorm [Jason Rusch/ Professor Martin Stein]": "Firestorm [Ronnie Raymond/ Professor Martin Stein]",
    "Firestorm [Ron Raymond/ Martin Stein]": "Firestorm [Ronnie Raymond/ Professor Martin Stein]",
    "Firestorm [Ronnie Raymond]": "Firestorm [Ronnie Raymond/ Professor Martin Stein]",
    "Firestorm [Ronnie Raymond/ Martin Stein]": "Firestorm [Ronnie Raymond/ Professor Martin Stein]",
    "Firestorm": "Firestorm [Ronnie Raymond/ Martin Stein]",
    "Firestorm": "Firestorm [Ronnie Raymond/ Professor Martin Stein]",
    "Flash (Wally West)": "Flash [Wally West]",
    "Flash [Walter West]": "Flash [Wally West]",
    "Flash": "Flash [Barry Allen]",
    "Flicker Holbrook": "Clicker Holbrook",
    "Frank Castle [Punisher]": "Punisher [Frank Castle]",
    "Frank Castle [The Punisher]": "Punisher [Frank Castle]",
    "Frankenstein Monster": "Frankenstein",
    "Frankenstein's Monster": "Frankenstein",
    "Frog Thor": "Throg",
    "Gambit [Remy LaBeau]": "Gambit [Remy Etienne LeBeau]",
    "Gambit [Remy Le Beau]": "Gambit [Remy Etienne LeBeau]",
    "Gambit [Remy LeBeau]": "Gambit [Remy Etienne LeBeau]",
    "Gambit [Remy Lebeau]": "Gambit [Remy Etienne LeBeau]",
    "Gambit": "Gambit [Remy Etienne LeBeau]",
    "Gargoyle": "Gargoyle [Isaac Christians]",
    "Geo-Force": "Geo-Force [Brion Markov]",
    "Geraldine Grundy": "Miss Grundy",
    "Ghost Rider [Dan Ketch]": "Ghost Rider [Danny Ketch]",
    "Ghost Rider [Dan Ketch]": "Ghost Rider [Danny Ketch]",
    "Ghost Rider [Daniel Ketch]": "Ghost Rider [Danny Ketch]",
    "Ghost Rider [Daniel Ketch]": "Ghost Rider [Danny Ketch]",
    "Ghost Rider [Johnny Storm]": "Ghost Rider [Johnny Blaze]",
    "Ghost Rider": "Ghost Rider [Johnny Blaze]",
    "Ghost Rider": "Ghost Rider [Johnny Blaze]",
    "Giant Man [Dr. Hank Pym]": "Goliath [Hank Pym]",
    "Giant Man [Hank Pym]": "Goliath [Hank Pym]",
    "Giant Man [Henry Pym]": "Goliath [Hank Pym]",
    "Giant Man": "Goliath [Hank Pym]",
    "Giant-Man [Hank Pym]": "Goliath [Hank Pym]",
    "Giant-Man [Henry Pym]": "Goliath [Hank Pym]",
    "Giant-Man": "Goliath [Hank Pym]",
    "God Emperor Doom [Victor von Doom/ Doctor Doom]": "Doctor Doom [Victor von Doom]",
    "Goliath [Henry Pym]": "Goliath [Hank Pym]",
    "Goofy [Super Goof]": "Goofy",
    "Gorgon": "Gorgon [Andonis Bal]",
    "Green Arrow (Earth-1)": "Green Arrow [Oliver Queen]",
    "Green Arrow (Earth-2)": "Green Arrow [Oliver Queen]",
    "Green Arrow [Oliver Queen] (Earth-1)": "Green Arrow [Oliver Queen]",
    "Green Arrow [Oliver Queen] (Earth-2)": "Green Arrow [Oliver Queen]",
    "Green Arrow": "Green Arrow [Oliver Queen]",
    "Green Goblin (Harry Osborn)": "Green Goblin [Norman Osborn]",
    "Green Goblin (Harry Osborn)": "Green Goblin [Norman Osborn]",
    "Green Goblin [Harry Osborn]": "Green Goblin [Norman Osborn]",
    "Green Goblin [Harry Osborn]": "Green Goblin [Norman Osborn]",
    "Green Goblin [Norman Osborn II]": "Green Goblin [Norman Osborn]",
    "Green Goblin [Norman Osborn II]": "Green Goblin [Norman Osborn]",
    "Green Goblin [Peter Parker]": "Green Goblin [Norman Osborn]",
    "Green Goblin [Phil Urich]": "Green Goblin [Norman Osborn]",
    "Green Goblin [Philip Urich]": "Green Goblin [Norman Osborn]",
    "Green Goblin": "Green Goblin [Norman Osborn]",
    "Green Lantern [Daffy Duck]": "Daffy Duck",
    "Green Lantern": "Green Lantern [Hal Jordan]",
    "Guido [Strong Guy]": "Strong Guy [Guido Carosella]",
    "Guido": "Strong Guy [Guido Carosella]",
    "Guy Gardner": "Green Lantern [Guy Gardner]",
    "Gwen Stacy [Spider-Woman]": "Spider-Woman [Gwen Stacy]",
    "Gwenpool [Gwen Poole]": "Gwenpool [Gwendolyne Poole]",
    "Gwenpool": "Gwenpool [Gwendolyne Poole]",
    "Gypsy [Cynnthia]": "Gypsy [Cynthia Reynolds]",
    "Gypsy": "Gypsy [Cynthia Reynolds]",
    "Hal Jordan [Green Lantern]": "Green Lantern [Hal Jordan]",
    "Hal Jordan": "Green Lantern [Hal Jordan]",
    "Halo": "Halo [Gabrielle Doe]",
    "Hammerhead": "Hammerhead [Louis Browning]",
    "Hank McCoy [Beast]": "Beast [Hank McCoy]",
    "Hank Pym": "Ant Man [Hank Pym]",
    "Harley Quinn": "Harley Quinn [Harleen Quinzel]",
    "Havok": "Havok [Alex Summers]",
    "Hawk": "Hawk [Hank Hall]",
    "Hawkeye [Bullseye]": "Hawkeye [Clint Barton]",
    "Hawkeye [Bullseye]": "Hawkeye [Clint Barton]",
    "Hawkeye": "Hawkeye [Clint Barton]",
    "Hawkgirl [Kendra Saunders]": "Hawkgirl [Shayera Thal]",
    "Hawkgirl [Kendra Suanders]": "Hawkgirl [Shayera Thal]",
    "Hawkgirl [Shayera Hol]": "Hawkgirl [Shayera Thal]",
    "Hawkgirl [Shiera Hall]": "Hawkgirl [Shayera Thal]",
    "Hawkgirl [Shiera Hall/ Shayera Hol]": "Hawkgirl [Shayera Thal]",
    "Hawkgirl [Shiera Sanders Hall]": "Hawkgirl [Shayera Thal]",
    "Hawkgirl [Shiera Sanders]": "Hawkgirl [Shayera Thal]",
    "Hawkgirl [Shiera Saunders]": "Hawkgirl [Shayera Thal]",
    "Hawkgirl": "Hawkgirl [Shayera Thal]",
    "Hawkgirl[Kendra Saunders]": "Hawkgirl [Shayera Thal]",
    "Hawkman [Carter Hal/ Katar Hol]": "Hawkman [Katar Hol/ Carter Hall]",
    "Hawkman [Carter Hall]": "Hawkman [Katar Hol/ Carter Hall]",
    "Hawkman [Carter Hall/ Katar Hol]": "Hawkman [Katar Hol/ Carter Hall]",
    "Hawkman [Katar Hol]": "Hawkman [Katar Hol/ Carter Hall]",
    "Hawkman": "Hawkman [Katar Hol/ Carter Hall]",
    "Hawkwoman [Shayera Hol]": "Hawkgirl [Shayera Thal]",
    "Hawkwoman [Shayera Thal]": "Hawkgirl [Shayera Thal]",
    "Hawkwoman": "Hawkgirl [Shayera Thal]",
    "Hellcat": "Hellcat [Patsy Walker]",
    "Hellstorm [Daimon Hellstrom]": "Son of Satan [Daimon Hellstrom]",
    "Hellstorm": "Son of Satan [Daimon Hellstrom]",
    "Hellstrom": "Son of Satan [Daimon Hellstrom]",
    "Henry Pym": "Doctor Pym [Henry Pym]",
    "Hitman": "Hitman [Tommy Monaghan]",
    "Hobgoblin [Flash Thompson]": "Hobgoblin [Roderick Kingsley]",
    "Hobgoblin [Harry Osborn]": "Hobgoblin [Roderick Kingsley]",
    "Hobgoblin [Jason Macendale Jr.]": "Hobgoblin [Roderick Kingsley]",
    "Hobgoblin [Jason Macendale]": "Hobgoblin [Roderick Kingsley]",
    "Hobgoblin [Ned Leeds]": "Hobgoblin [Roderick Kingsley]",
    "Hobgoblin [Phil Urich]": "Hobgoblin [Roderick Kingsley]",
    "Hobgoblin": "Hobgoblin [Roderick Kingsley]",
    "Hourman": "Hourman [Rex Tyler]",
    "Howard The Duck": "Howard the Duck",
    "Hulk [Dr. Bruce Banner]": "Hulk [Bruce Banner]",
    "Hulk [Jennifer Walters]": "She-Hulk [Jennifer Walters]",
    "Hulk [Ross]": 'Red Hulk [Thaddeus E. "Thunderbolt" Ross]',
    "Hulk": "Hulk [Bruce Banner]",
    "Human Bomb": "Human Bomb [Dave Mathis]",
    "Human Torch [Human Torch]": "Human Torch [Johnny Storm]",
    "Human Torch [Johhny Storm]": "Human Torch [Johnny Storm]",
    "Human Torch [John Storm]": "Human Torch [Johnny Storm]",
    "Human Torch": "Human Torch [Johnny Storm]",
    "Huntress [Helena Wayne]": "Huntress [Helena Bertinelli]",
    "Huntress": "Huntress [Helena Bertinelli]",
    "Husk": "Husk [Paige Guthrie]",
    "Hyperion [Marcus Milton] (Earth-13034)": "Hyperion [Mark Milton]",
    "Hyperion": "Hyperion [Mark Milton]",
    "Ice Man": "Iceman [Bobby Drake]",
    "Ice-Man [Robert Drake]": "Iceman [Bobby Drake]",
    "Ice-Man": "Iceman [Bobby Drake]",
    "Ice": "Ice [Tora Olafsdotter]",
    "Iceman [Robert Drake]": "Iceman [Bobby Drake]",
    "Iceman": "Iceman [Bobby Drake]",
    "Impulse": "Impulse [Bart Allen]",
    "Invisble Woman [Susan Storm]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Girl [Sue Richards]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Girl [Sue Storm Richards]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Girl [Sue Storm]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Girl [Susan Storm Richards]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Girl [Susan Storm]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Girl": "Invisible Woman [Sue Storm Richards]",
    "Invisible Kid": "Invisible Kid [Jacques Foccart]",
    "Invisible Kid": "Invisible Kid [Lyle Norg]",
    "Invisible Woman [Sue Richards Storm]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Woman [Sue Richards]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Woman [Sue Storm Richards]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Woman [Sue Storm]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Woman [Susan Richards]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Woman [Susan Storm Richards]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Woman [Susan Storm]": "Invisible Woman [Sue Storm Richards]",
    "Invisible Woman": "Invisible Woman [Sue Storm Richards]",
    "Iron Fist [Daniel Rand]": "Iron Fist [Danny Rand]",
    "Iron Fist": "Iron Fist [Danny Rand]",
    "Iron Man": "Iron Man [Tony Stark]",
    "Iron Patriot [Dr. Toni Ho]": "Iron Patriot [Norman Osborn]",
    "Iron Patriot [James Rhodes]": "Iron Patriot [Norman Osborn]",
    "Iron Patriot [Jim Rhodes]": "Iron Patriot [Norman Osborn]",
    "Iron Patriot [Toni Ho]": "Iron Patriot [Norman Osborn]",
    "Iron Patriot": "Iron Patriot [Norman Osborn]",
    "J. Jonah Jameson Sr.": "J. Jonah Jameson",
    "J. Jonah Jameson, Sr.": "J. Jonah Jameson",
    "J'onn J'onzz": "Martian Manhunter [J'onn J'onzz]",
    "Jade": "Jade [Jennie-Lynn Hayden]",
    "Jane Foster, Goddess of Thunder": "Thor [Jane Foster]",
    "Jean Gray": "Marvel Girl [Jean Grey]",
    "Jean Grey [Marvel Girl]": "Marvel Girl [Jean Grey]",
    "Jean Grey": "Marvel Girl [Jean Grey]",
    "Jean Paul Valley [Azrael]": "Azrael [Jean Paul Valley]",
    "Jericho [Joe Wilson]": "Jericho [Joseph Wilson]",
    "Jericho": "Jericho [Joe Wilson]",
    "Jessica Drew [Spider-Woman]": "Spider-Woman [Jessica Drew]",
    "Jimmy Olsen (headshot)": "Jimmy Olsen",
    "Joe Fixit [Hulk/ Bruce Banner]": "Hulk [Joe Fixit]",
    "John Constantine [Hellblazer]": "Hellblazer [John Constantine]",
    "John Constantine": "Hellblazer [John Constantine]",
    "John Stewart": "Green Lantern [John Stewart]",
    "Johnny Quick": "Johnny Quick [Johnny Chambers]",
    "Johnny Storm [Human Torch]": "Human Torch [Johnny Storm]",
    "Johnny Storm": "Human Torch [Johnny Storm]",
    "Johnny Thunder (Earth-2)": "Johnny Thunder",
    "Jonah Jameson": "J. Jonah Jameson",
    "Jubilee": "Jubilee [Jubilation Lee]",
    "Juggernaut": "Juggernaut [Cain Marko]",
    "Julie Power [Lightspeed]": "Lightspeed [Julie Power]",
    "Julie Power": "Lightspeed [Julie Power]",
    "June Moone [Enchantress]": "Enchantress [June Moone]",
    "Ka-Zar": "Ka-Zar [Kevin Plunder]",
    "Kamala Kahn [Ms. Marvel]": "Ms. Marvel [Kamala Khan]",
    "Kamala Khan [Ms. Marvel]": "Ms. Marvel [Kamala Khan]",
    "Kang": "Kang the Conqueror",
    "Karate Kid": "Karate Kid [Val Armorr]",
    "Karolina Dean": "Karolina Dean [Lucy in the Sky]",
    "Katana": "Katana [Tatsu Yamashiro]",
    "Kate Bishop [Hawkeye]": "Hawkeye [Kate Bishop]",
    "Kate Bishop": "Hawkeye [Kate Bishop]",
    "Katie Bishop": "Hawkeye [Kate Bishop]",
    "Katie Power [Energizer]": "Energizer [Katie Power]",
    "Katie Power": "Energizer [Katie Power]",
    "KGBeast": "KGBeast [Anatoli Knyazev]",
    "Kid Colt": "Kid Colt [Blaine Colt]",
    "Kid Devil [Edward Bloomberg]": "Kid Devil [Eddie Bloomberg]",
    "Kid Devil": "Kid Devil [Eddie Bloomberg]",
    "Kid Flash [Bart Allen/ also as Bar Torr]": "Kid Flash [Bart Allen]",
    "Kid Flash [Wally K. West]": "Kid Flash [Wally West]",
    "Kid Flash [Wally R. West]": "Kid Flash [Wally West]",
    "Kid Flash [Wally West (new)]": "Kid Flash [Wally West]",
    "Kid Flash [Wally West (young)]": "Kid Flash [Wally West]",
    "Kid Flash": "Kid Flash [Wally West]",
    "Kid Quantum": "Kid Quantum [Jazmin Cullen]",
    "Killer Croc": "Killer Croc [Waylon Jones]",
    "Killer Frost [Caitlin Snow]": "Killer Frost [Crystal Frost]",
    "Killer Frost [Louise Lincoln]": "Killer Frost [Crystal Frost]",
    "Killer Frost": "Killer Frost [Crystal Frost]",
    "Killer Shark": "Killer Shark [General Haifisch]",
    "Killraven": "Killraven [Jon Raven]",
    "Kilowog": "Green Lantern [Kilowog]",
    "King Shark": "King Shark [Nanaue]",
    "Kingpin": "Kingpin [Wilson Fisk]",
    "Kitty Pryde": "Kitty Pryde [Shadowcat]",
    "Korak": "Korak [Jack Clayton]",
    "Kraven the Hunter": "Kraven [Sergei Kravinoff]",
    "Kraven": "Kraven [Sergei Kravinoff]",
    "Kyle Richmond [Nighthawk]": "Nighthawk [Kyle Richmond]",
    "Lady Blackhawk [Zinda Blake]": "Blackhawk",
    "Lady Blackhawk": "Blackhawk",
    "Lady Deathstrike": "Lady Deathstrike [Yuriko Oyama]",
    "Laura Kinney [X-23]": "Wolverine [X-23/ Laura Kinney]",
    "Leia Organa Solo": "Princess Leia Organa",
    "Leia Organa": "Princess Leia Organa",
    "Lex Luthor (Earth-1)": "Lex Luthor",
    "Lex Luthor (Earth-2)": "Lex Luthor",
    "Light Lass [Ayla Ranzz]": "Lightning Lass [Ayla Ranzz]",
    "Light Lass": "Lightning Lass [Ayla Ranzz]",
    "Lightning Lad [Gart Ranzz]": "Lightning Lad [Garth Ranzz]",
    "Lightning Lad": "Lightning Lad [Garth Ranzz]",
    "Lightning Lad": "Lightning Lad [Garth Ranzz]",
    "Lightning Lass": "Lightning Lass [Ayla Ranzz]",
    "Lightspeed": "Lightspeed [Julie Power]",
    "Livewire": "Live Wire",
    "Lizard [Doctor Curt Connors]": "Lizard [Curt Connors]",
    "Lizard": "Lizard [Curt Connors]",
    "Logan [Wolverine]": "Wolverine [Logan/ James Howlett]",
    "Logan": "Wolverine [Logan/ James Howlett]",
    "Lois Lane (Earth 1)": "Lois Lane",
    "Lois Lane (Earth 2)": "Lois Lane",
    "Lois Lane (Earth-2)": "Lois Lane",
    "Lois Lane Kent": "Lois Lane",
    "Lois Lane-Kent (Earth-2)": "Lois Lane",
    "Loki Laufeyson": "Loki [Loki Laufeyson]",
    "Loki": "Loki [Loki Laufeyson]",
    "Looker [Lia Briggs]": "Looker [Emily Briggs]",
    "Looker": "Looker [Emily Briggs]",
    "Lorna Dane [Polaris]": "Polaris [Lorna Dane]",
    "Luke Cage [Power Man]": "Power Man [Luke Cage]",
    "Luke Cage": "Power Man [Luke Cage]",
    "Lunella Lafayette [Moon Girl]": "Moon Girl [Lunella Lafayette]",
    "Lunella Layfayette [Moon Girl]": "Moon Girl [Lunella Lafayette]",
    "M [Monet St. Croix]": "Monet [Monet Yvette Clarisse Maria Therese St. Croix]",
    "M [Monet St. Croix]": "Monet [Monet Yvette Clarisse Maria Therese St. Croix]",
    "M": "Monet [Monet Yvette Clarisse Maria Therese St. Croix]",
    "Mad Doctor Doom": "Doctor Doom [Victor von Doom]",
    "Madame Xanadu [Nimue]": "Madame Xanadu",
    "Madrox Gang": "Multiple Man [Jamie Madrox]",
    "Madrox the Multiple Man": "Multiple Man [Jamie Madrox]",
    "Magneto [Eric Lehnsherr]": "Magneto [Erik Lehnsherr]",
    "Magneto [Eric Lensherr]": "Magneto [Erik Lehnsherr]",
    "Magneto [Erik Lensherr]": "Magneto [Erik Lehnsherr]",
    "Magneto": "Magneto [Erik Lehnsherr]",
    "Major Victory": "Major Victory [Vance Astro]",
    "Man-Bat": "Man-Bat [Kirk Langstrom]",
    "Man-Thing [Ted Sallis]": "Man-Thing",
    "Manhunter [Chase Lawler]": "Manhunter [Mark Shaw]",
    "Manhunter [Paul Kirk]": "Manhunter [Mark Shaw]",
    "Manhunter": "Manhunter [Mark Shaw]",
    "Manta": "Black Manta",
    "Marionette": "Marionette [Princess Mari]",
    "Martian Manhunter [J'Onn J'Onzz]": "Martian Manhunter [J'onn J'onzz]",
    "Martian Manhunter": "Martian Manhunter [J'onn J'onzz]",
    "Martian Manhutner [J'onn J'onzz]": "Martian Manhunter [J'onn J'onzz]",
    "Marvel Boy [Vance Astro]": "Justice [Vance Astrovik]",
    "Marvel Boy [Vance Astrovik]": "Justice [Vance Astrovik]",
    "Marvel Girl": "Marvel Girl [Jean Grey]",
    "Marvel Man [Vance Astrovik]": "Justice [Vance Astrovik]",
    "Mary Jane Parker": "Mary Jane Watson",
    "Mary Jane Watson Parker": "Mary Jane Watson",
    "Mary Jane Watson-Parker": "Mary Jane Watson",
    "Mary Jane": "Mary Jane Watson",
    "Master of Kung Fu [Shang-Chi]": "Shang-Chi",
    "Matt Murdock [Daredevil]": "Daredevil [Matt Murdock]",
    "May Parker [Spider-Girl]": "Spider-Girl [May Parker]",
    "May Parker": "Aunt May Parker",
    "Medusa [Medusalith Amaquelin Boltagon]": "Medusa [Medusalith Amaquelin]",
    "Medusa [Medusalith Amaquelin-Boltagon]": "Medusa [Medusalith Amaquelin]",
    "Medusa [Medusalith Amequelin]": "Medusa [Medusalith Amaquelin]",
    "Medusa [Medusalith Amequilin]": "Medusa [Medusalith Amaquelin]",
    "Medusa": "Medusa [Medusalith Amaquelin]",
    "Meggan": "Meggan [Meggan Puceanu]",
    "Melody": "Melody Valentine",
    "Metamorpho": "Metamorpho [Rex Mason]",
    "Metamorpho": "Metamorpho [Rex Mason]",
    "Midnighter": "Midnighter [Lucas Trent]",
    "Mimic": "Mimic [Calvin Rankin]",
    "Mirage [Danielle Moonstar]": "Mirage [Dani Moonstar]",
    "Mirror Master [Sam Scudder]": "Mirror Master [Evan McCulloch]",
    "Mirror Master": "Mirror Master [Evan McCulloch]",
    "Miss Martian [Megan Morse]": "Miss Martian [M'gann M'orzz]",
    "Miss Martian": "Miss Martian [M'gann M'orzz]",
    "Miss Marvel [Kamala Khan]": "Ms. Marvel [Kamala Khan]",
    "Mister Fantastic [Reed Richards]": "Mr. Fantastic [Reed Richards]",
    "Mister Fantastic": "Mr. Fantastic [Reed Richards]",
    "Mister Miracle": "Mister Miracle [Scott Free]",
    "Mister Terrific [Michael Holt]": "Mr. Terrific [Michael Holt]",
    "Mister Terrific": "Mr. Terrific [Michael Holt]",
    "Mockingbird": "Mockingbird [Bobbi Morse]",
    "Mon-El": "Mon-El [Lar Gand]",
    "Monet": "Monet [Monet Yvette Clarisse Maria Therese St. Croix]",
    "Moon Girl [Lunetta Lafayette]": "Moon Girl [Lunella Lafayette]",
    "Moon Girl": "Moon Girl [Lunella Lafayette]",
    "Moon Knight [Marc Spector]": "Moon Knight",
    "Moondragon": "Moondragon [Heather Douglas]",
    "Moonstone [Karla Sofen]": "Moonstone [Dr. Karla Sofen]",
    "Moonstone": "Moonstone [Dr. Karla Sofen]",
    "Morph": "Morph [Benjamin Deeds]",
    "Mr. Fantastic": "Mr. Fantastic [Reed Richards]",
    "Mr. Flutesnoot": "Professor Flutesnoot",
    "Mr. Miracle [Scott Free]": "Mister Miracle [Scott Free]",
    "Mr. Miracle": "Mister Miracle [Scott Free]",
    "Mr. Terrific": "Mr. Terrific [Terry Sloane]",
    "Mrs. Grundy": "Miss Grundy",
    "Ms. Grundy": "Miss Grundy",
    "Ms. Marvel [Kamala Kahn]": "Ms. Marvel [Kamala Khan]",
    "Ms. Marvel [Kamala Kahn]": "Ms. Marvel [Kamala Khan]",
    "Ms. Marvel [Kamala Khan]": "Ms. Marvel [Kamala Khan]",
    "Ms. Marvel": "Ms. Marvel [Carol Danvers]",
    "Multiple Man": "Multiple Man [Jamie Madrox]",
    "Mysterio": "Mysterio [Quentin Beck]",
    "Mystique [Raven Darkholm]": "Mystique [Raven Darkholme]",
    "Mystique [Raven Darkhölme]": "Mystique [Raven Darkholme]",
    "Mystique": "Mystique [Raven Darkholme]",
    "Namor [Sub-Mariner]": "Sub-Mariner [Namor]",
    "Namor the Sub-Mariner": "Sub-Mariner [Namor]",
    "Namor, the Sub-Mariner": "Sub-Mariner [Namor]",
    "Namor, The Sub-Mariner": "Sub-Mariner [Namor]",
    "Namor": "Sub-Mariner [Namor]",
    "Namorita": "Kymaera [Namorita]",
    "Natasha Romanova [Black Widow]": "Black Widow [Natasha Romanov]",
    "Nathan Christopher Summers [Cable/ Nathan Dayspring": "Cable [Nathan Summers]",
    "Nathan Dayspring [Cable]": "Cable [Nathan Summers]",
    "Negative Man": "Negative Man [Larry Trainor]",
    "Nick Fury Jr.": "Nick Fury, Jr.",
    "Nick Fury L.M.D.": "Nick Fury",
    "Nick Fury LMD": "Nick Fury",
    "Nick Fury, Sr.": "Nick Fury",
    "Nico Minoru [Sister Grimm]": "Nico Minoru [Sister Grimm]",
    "Nico Minoru": "Nico Minoru [Sister Grimm]",
    "Night Thrasher": "Night Thrasher [Donyell Taylor]",
    "Nightcrawler (Earth-295)": "Nightcrawler [Kurt Wagner]",
    "Nightcrawler [Kurt Logan]": "Nightcrawler [Kurt Wagner]",
    "Nightcrawler": "Nightcrawler [Kurt Wagner]",
    "Nighthawk [Kyle Richmond] (Earth-31916)": "Nighthawk [Kyle Richmond]",
    "Nighthawk": "Nighthawk [Kyle Richmond]",
    "Nighthawk": "Nighthawk [Kyle Richmond]",
    "Nightshade": "Nightshade [Eve Eden]",
    "Nightwing [Dick Grayson/ also as Robin]": "Nightwing [Dick Grayson]",
    "Nightwing [Richard Grayson]": "Nightwing [Dick Grayson]",
    "Nightwing": "Nightwing [Dick Grayson]",
    "Nigthcrawler": "Nightcrawler [Kurt Wagner]",
    "Norman Osborn [as Spider-Man]": "Spider-Man [Peter Parker]",
    "Norman Osborn [Green Goblin]": "Green Goblin [Norman Osborn]",
    "Northstar": "Northstar [Jean-Paul Beaubier]",
    "Nova [Rich Rider]": "Nova [Richard Rider]",
    "Nova [Richard Ryder]": "Nova [Richard Rider]",
    "Nova": "Nova [Richard Rider]",
    "Obsidian": "Obsidian [Todd Rice]",
    "Old Man Logan [Logan]": "Old Man Logan [James Howlett]",
    "Old Man Logan [Wolverine]": "Old Man Logan [James Howlett]",
    "Old Man Logan": "Old Man Logan [James Howlett]",
    "OLd Man Logan": "Old Man Logan [James Howlett]",
    "Oliver Queen [Green Arrow]": "Green Arrow [Oliver Queen]",
    "Oracle": "Oracle [Barbara Gordon]",
    "Ororo Munroe [Storm]": "Storm [Ororo Munroe]",
    "Pamela Isley [Poison Ivy]": "Poison Ivy [Pamela Isley]",
    "Patsy Walker [Hellcat]": "Hellcat [Patsy Walker]",
    "Patsy Walker [Hellcat]": "Hellcat [Patsy Walker]",
    "Patsy Walker": "Hellcat [Patsy Walker]",
    "Patsy": "Hellcat [Patsy Walker]",
    "Penguin": "Penguin [Oswald Cobblepot]",
    "Peter Parker [Spider-Man]": "Spider-Man [Peter Parker]",
    "Peter Quill [Star-Lord]": "Star-Lord [Peter Quill]",
    "Phantom Blot": "The Phantom Blot",
    "Phantom Girl [Linnya Wazzo]": "Phantom Girl [Tinya Wazzo]",
    "Phantom Girl": "Phantom Girl [Tinya Wazzo]",
    "Phantom Lady": "Phantom Lady [Sandra Knight]",
    "Phantomex": "Fantomex",
    "Phil Urich [Green Goblin]": "Green Goblin [Norman Osborn]",
    "Phoenix [Jean Grey]": "Marvel Girl [Jean Grey]",
    "Plastic Man": "Plastic Man [Eel O'Brian]",
    "Poison Ivy": "Poison Ivy [Pamela Isley]",
    "Polaris": "Polaris [Lorna Dane]",
    "Popeye": "Popeye the Sailor",
    "Power Girl [Tanya Spears]": "Power Girl [Karen Starr]",
    "Power Girl": "Power Girl [Karen Starr]",
    "Power Man": "Power Man [Luke Cage]",
    "Power Princess [Earth-S]": "Power Princess [Zarda Shelton]",
    "Power Princess [Zarda Shelton] (Earth-712)": "Power Princess [Zarda Shelton]",
    "Power Princess [Zarda]": "Power Princess [Zarda Shelton]",
    "Power Princess": "Power Princess [Zarda Shelton]",
    "Prestige": "Prestige [Rachel Grey]",
    "Prime Sentinels": "Sentinels",
    "Princess Diana [Wonder Woman]": "Wonder Woman [Diana Prince]",
    "Princess Leia Organa Solo": "Princess Leia Organa",
    "Princess Leia Organa-Solo": "Princess Leia Organa",
    "Princess Leia": "Princess Leia Organa",
    "Princess Python": "Princess Python [Zelda DuBois]",
    "Prof Haley": "Professor Haley",
    "Prof. Flutesnoot": "Professor Flutesnoot",
    "Prof. Haley": "Professor Haley",
    "Professor [Charles Xavier]": "Professor X [Charles Xavier]",
    "Professor Charles Xavier": "Professor X [Charles Xavier]",
    "Professor X": "Professor X [Charles Xavier]",
    "Professor Xavier": "Professor X [Charles Xavier]",
    "Professor Zoom [Eobard Thawne]": "Reverse-Flash [Professor Zoom/ Eobard Thawne]",
    "Professor Zoom [Reverse-Flash/ Eobard Thawne]": "Reverse-Flash [Professor Zoom/ Eobard Thawne]",
    "Professor Zoom": "Reverse-Flash [Professor Zoom/ Eobard Thawne]",
    "Psylocke [Betsy Braddock]": "Psylocke [Elizabeth Braddock]",
    "Psylocke [Elisabeth Braddock]": "Psylocke [Elizabeth Braddock]",
    "Psylocke": "Psylocke [Elizabeth Braddock]",
    "Puck": "Puck [Eugene Judd]",
    "Punisher [Frank Castelione Jr.]": "Punisher [Frank Castle]",
    "Punisher [Jake Gallows]": "Punisher 2099 [Jake Gallows]",
    "Punisher 2099 [Jack Gallows]": "Punisher 2099 [Jake Gallows]",
    "Punisher 2099": "Punisher 2099 [Jake Gallows]",
    "Punisher": "Punisher [Frank Castle]",
    "Quasar": "Quasar [Wendell Vaughn]",
    "Question [Vic Sage]": "The Question [Vic Sage]",
    "Question": "The Question [Vic Sage]",
    "Quicksilver": "Quicksilver [Pietro Maximoff]",
    "Ra's Al Ghul": "Ra's al Ghul",
    "Rachel Grey": "Prestige [Rachel Grey]",
    "Rahne [Wolfsbane]": "olfsbane [Rahne]",
    "Rahne Sinclair [Wolfsbane]": "Wolfsbane [Rahne Sinclair]",
    "Raven [Rachel]": "Raven [Rachel Roth]",
    "Raven": "Raven [Rachel Roth]",
    "Red Arrow": "Red Arrow [Roy Harper]",
    "Red Ghost": "Red Ghost [Ivan Kragoff]",
    "Red Goblin / Green Goblin [Norman Osborn]": "Red Goblin [Norman Osborn]",
    "Red Goblin": "Red Goblin [Norman Osborn]",
    "Red Hood": "Red Hood [Jason Todd]",
    "Red Hulk [General Robert L. Maverick]": 'Red Hulk [Thaddeus E. "Thunderbolt" Ross]',
    "Red Hulk [General Ross]": 'Red Hulk [Thaddeus E. "Thunderbolt" Ross]',
    "Red Hulk": 'Red Hulk [Thaddeus E. "Thunderbolt" Ross]',
    "Red Robin": "Red Robin [Tim Drake]",
    "Red She-Hulk": "Red She-Hulk [Betty Ross]",
    "Red She-Hulk": "Red She-Hulk [Betty Ross]",
    "Red Skull": "Red Skull [Johann Schmidt]",
    "Red Tornado": "Red Tornado [John Smith]",
    "Reed Richards [Mr. Fantastic]": "Mr. Fantastic [Reed Richards]",
    "Reverse Flash [Professor Zoom]": "Reverse-Flash [Professor Zoom/ Eobard Thawne]",
    "Reverse-Flash": "Reverse-Flash [Daniel West]",
    "Rex Mason [Metamorpho]": "Metamorpho [Rex Mason]",
    "Rhino [Aleksei Sytsevich]": "Rhino [Aleksei Mikhailovich Sytsevich]",
    "Rhino": "Rhino [Aleksei Mikhailovich Sytsevich]",
    "Rictor": "Rictor [Julio Esteban Richter]",
    "Riddler [Edward Nygma]": "Riddler [Edward Nigma]",
    "Riddler": "Riddler [Edward Nigma]",
    "Rita Farr [Elasti-Woman]": "Elasti-Girl [Rita Farr]",
    "Robert Ralston": "Robert Ralston [Rebel Ralston]",
    "Robin [Bruce Wayne, Jr.]": "Robin [Damian Wayne]",
    "Robin [Damien Wayne]": "Robin [Damian Wayne]",
    "Robin": "Robin [Dick Grayson]",
    "Robotman [Clifford Steele]": "Robotman [Cliff Steele]",
    "Robotman": "Robotman [Cliff Steele]",
    "Rocket Racoon": "Rocket Raccoon",
    "Rocket": "Rocket Raccoon",
    "Rockslide": "Rockslide [Santo Vaccarro]",
    "Rogue [Ana Marie Raven]": "Rogue [Anna Marie Raven]",
    "Rogue [Ann Marie LeBeau]": "Rogue [Anna Marie Raven]",
    "Rogue [Ann Marie]": "Rogue [Anna Marie Raven]",
    "Rogue [Anna Marie]": "Rogue [Anna Marie Raven]",
    "Rogue [Anne Marie]": "Rogue [Anna Marie Raven]",
    "Rogue [Marie]": "Rogue [Anna Marie Raven]",
    "Rogue": "Rogue [Anna Marie Raven]",
    "Sabretooth (Earth-295)": "Sabretooth [Victor Creed]",
    "Sabretooth Clones": "Sabretooth [Victor Creed]",
    "Sabretooth": "Sabretooth [Victor Creed]",
    "Sabrina": "Sabrina Spellman",
    "Sam Wilson [Captain America]": "Captain America [Sam Wilson]",
    "Sandman [Wesley Dodds]": "Sandman [Wes Dodds]",
    "Sandman": "Sandman [Wes Dodds]",
    "Sasquatch [Dr. Walter Langkowski]": "Sasquatch [Walter Langkowski]",
    "Sasquatch [Wanda Langkowski]": "Sasquatch [Walter Langkowski]",
    "Sasquatch": "Sasquatch [Walter Langkowski]",
    "Saturn Girl": "Saturn Girl [Imra Ardeen]",
    "Scarecrow": "Scarecrow [Jonathan Crane]",
    "Scarlet Spider": "Scarlet Spider [Ben Reilly]",
    "Scarlet Witch [Wanda Miximoff]": "Scarlet Witch [Wanda Maximoff]",
    "Scarlet Witch": "Scarlet Witch [Wanda Maximoff]",
    "Scott Free [Mister Miracle]": "Mister Miracle [Scott Free]",
    "Scott Free [Mr. Miracle]": "Mister Miracle [Scott Free]",
    "Scott Summers [Cyclops]": "Cyclops [Scott Summers]",
    "Selina Kyle [Catwoman]": "Catwoman [Selina Kyle]",
    "Sensor Girl [Projectra]": "Princess Projectra",
    "Sentry": "Sentry [Robert Reynolds]",
    "Sergeant Nick Fury": "Nick Fury",
    "Sgt. Nick Fury": "Nick Fury",
    "Sgt. Rock": "Sgt. Rock [Frank Rock]",
    "Shadow Cat [Kitty Pryde]": "Kitty Pryde",
    "Shadow Lass": "Shadow Lass [Tasmia Mallor]",
    "Shadowcat [Kitty Pryde]": "Kitty Pryde",
    "Shadowman [Maxim St. James]": "Shadowman [Jack Boniface]",
    "Shadowman [Zero]": "Shadowman [Jack Boniface]",
    "Shadowman": "Shadowman [Jack Boniface]",
    "Shang Chi": "Shang-Chi",
    "Shatterstar": "Shatterstar [Gaveedra Seven]",
    "Shazam": "Shazam [Billy Batson]",
    "She-Hulk [Jen Walters]": "She-Hulk [Jennifer Walters]",
    "She-Hulk [Lyra Walters]": "She-Hulk [Jennifer Walters]",
    "She-Hulk [Lyra]": "She-Hulk [Lyra Walters]",
    "She-Hulk": "She-Hulk [Jennifer Walters]",
    "Shield": "Shield [Joe Higgins]",
    "Shining Knight [Justin]": "Shining Knight [Sir Ystin]",
    "Shining Knight": "Shining Knight [Sir Ystin]",
    "Shocker": "Shocker [Herman Schultz]",
    "Shrinking Violet": "Shrinking Violet [Salu Digby]",
    "Silver Sable": "Silver Sable [Silver Sablinova]",
    "Silver Surfer": "Silver Surfer [Norrin Radd]",
    "Siryn": "Siryn [Theresa Rourke Cassidy]",
    "Sister Grimm [Nico Minoru]": "Nico Minoru [Sister Grimm]",
    "Skids": "Skids [Sally Blevins]",
    "Solomon Grundy [Cyrus Gold]": "Solomon Grundy",
    "Son of Satan [Diamon Hellstrom]": "Son of Satan [Daimon Hellstrom]",
    "Son of Satan": "Son of Satan [Daimon Hellstrom]",
    "Songbird [Screaming Mimi]": "Songbird [Melissa Gold]",
    "Songbird": "Songbird [Melissa Gold]",
    "Sonic The Hedgehog": "Sonic the Hedgehog",
    "Sonic": "Sonic the Hedgehog",
    "Spawn [Jim Downing]": "Spawn [Al Simmons]",
    "Spawn": "Spawn [Al Simmons]",
    "Spectre [Hal Jordan]": "The Spectre [Hal Jordan]",
    "Spectre": "Spectre [Jim Corrigan]",
    "Speedball [Rob Baldwin]": "Speedball [Robbie Baldwin]",
    "Speedball": "Speedball [Robbie Baldwin]",
    "Speedy": "Speedy [Roy Harper]",
    "Spider-Girl": "Spider-Girl [May Parker]",
    "Spider-Gwen": "Spider-Gwen [Gwen Stacy]",
    "Spider-Ham": "Spider-Ham [Peter Porker]",
    "Spider-Man [Jim Osborn]": "Spider-Man [Peter Parker]",
    "Spider-Man [Otto Octavius]": "Spider-Man [Peter Parker]",
    "Spider-man [Peter Parker]": "Spider-Man [Peter Parker]",
    "Spider-Man 2099": "Spider-Man 2099 [Miguel O'Hara]",
    "Spider-Man Clone [Ben Reilly]": "Spider-Man [Ben Reilly]",
    "Spider-Man": "Spider-Man [Peter Parker]",
    "Spider-Woman [Gwen Stacy/ Spider-Gwen] (Earth-65)": "Spider-Woman [Gwen Stacy]",
    "Spider-Woman [Gwen Stacy/ Spider-Gwen]": "Spider-Woman [Gwen Stacy]",
    "Spider-Woman [Gwendolyne Stacy (Earth-65)/ Spider-Gwen]": "Spider Woman [Gwendolyne Stacy/ Spider-Gwen]",
    "Spider-Woman [Gwendolyne Stacy]": "Spider-Woman [Gwen Stacy]",
    "Spider-Woman [Gwendolyne Stacy/ Spider-Gwen] (Earth 65)": "Spider-Woman [Gwen Stacy]",
    "Spider-Woman [Gwendolyne Stacy/ Spider-Gwen] (Earth-65)": "Spider-Woman [Gwen Stacy]",
    "Spider-Woman [Gwendolyne Stacy/ Spider-Gwen]": "Spider-Woman [Gwen Stacy]",
    "Spider-Woman": "Spider-Woman [Jessica Drew]",
    "Spitfire": "Spitfire [Jacqueline Falsworth]",
    "Squirrel Girl": "Squirrel Girl [Doreen Green]",
    "Star Sapphire [Yrra Cynril/ also as Fatality]": "Star Sapphire [Carol Ferris]",
    "Star Sapphire": "Star Sapphire [Carol Ferris]",
    "Star-Lord [Peter Jason Quill]": "Star-Lord [Peter Quill]",
    "Star-Lord": "Star-Lord [Peter Quill]",
    "Star-Spangled Kid": "Star-Spangled Kid [Courtney Whitmore]",
    "Starfire [Koriand'r/ Kory Anders]": "Starfire [Koriand'r]",
    "Starfire [Princess Koriand'r]": "Starfire [Koriand'r]",
    "Starfire": "Starfire [Koriand'r]",
    "Starfox": "Starfox [Eros]",
    "Stargirl": "Stargirl [Courtney Whitmore]",
    "Starhawk": "Starhawk [Stakar Ogord]",
    "Starlord": "Star-Lord [Peter Quill]",
    "Starman": "Starman [Thom Kallor]",
    "Steel": "Steel [John Henry Irons]",
    "Stephen Strange": "Doctor Strange [Stephen Strange]",
    "Steve Rogers": "Captain America [Steve Rogers]",
    "Storm [Ororo Iqadi T'Challa]": "Storm [Ororo Munroe]",
    "Storm [Ororo Monroe]": "Storm [Ororo Munroe]",
    "Storm [Ororo]": "Storm [Ororo Munroe]",
    "Storm": "Storm [Ororo Munroe]",
    "Strong Guy [Guido]": "Strong Guy [Guido Carosella]",
    "Strong Guy": "Strong Guy [Guido Carosella]",
    "Stupor Duck [Daffy Duck]": "Daffy Duck",
    "Sub-Mariner [Namor McKenzie]": "Sub-Mariner [Namor]",
    "Sub-Mariner [Prince Namor]": "Sub-Mariner [Namor]",
    "Sub-Mariner": "Sub-Mariner [Namor]",
    "Sue Richards [Invisible Girl]": "Invisible Woman [Sue Storm Richards]",
    "Sue Richards [Invisible Girl]": "Invisible Woman [Sue Storm Richards]",
    "Sue Storm": "Invisible Woman [Sue Storm Richards]",
    "Sun Boy": "Sun Boy [Dirk Morgna]",
    "Sun Girl": "Sun Girl [Deborah Morgna]",
    "Sunfire": "Sunfire [Shiro Yoshida]",
    "Sunspot": "Sunspot [Roberto da Costa]",
    "Super Goof [Goofy]": "Goofy",
    "Superboy [Clark Kent]": "Superboy [Kal-El/ Clark Kent]",
    "Superboy [Clark Kent/ Kal-El]": "Superboy [Kal-El/ Clark Kent]",
    "Superboy [Conner Kent]": "Superboy [Conner Kent/ Kon-El]",
    "Superboy [Connor Kent]": "Superboy [Conner Kent/ Kon-El]",
    "Superboy [Jon Lane Kent]": "Superboy [Jon Kent]",
    "Superboy [Jonathan Kent]": "Superboy [Jon Kent]",
    "Superboy [Kal-El]": "Superboy [Kal-El/ Clark Kent]",
    "Superboy [Kon-El]": "Superboy [Conner Kent/ Kon-El]",
    "Superboy [Kon-El/ also as Connor Kent]": "Superboy [Conner Kent/ Kon-El]",
    "Superboy [Kon-El/ Conner Kent]": "Superboy [Conner Kent/ Kon-El]",
    "Superboy": "Superboy [Kal-El/ Clark Kent]",
    "Supergirl [Kara Danvers]": "Supergirl [Kara Danvers/ Kara Zor-El]",
    "Supergirl [Kara Zor-El]": "Supergirl [Kara Danvers/ Kara Zor-El]",
    "Supergirl [Kara Zor-El/ Kara Danvers]": "Supergirl [Kara Danvers/ Kara Zor-El]",
    "Supergirl [Kara Zor-El/ Linda Danvers]": "Supergirl [Kara Danvers/ Kara Zor-El]",
    "Supergirl [Kara Zor-El/ Linda Lang]": "Supergirl [Kara Danvers/ Kara Zor-El]",
    "Supergirl [Kara]": "Supergirl [Kara Danvers/ Kara Zor-El]",
    "Supergirl [Linda Danvers]": "Supergirl [Kara Danvers/ Kara Zor-El]",
    "Supergirl [Linda Danvers/ Kara Zor-El]": "Supergirl [Kara Danvers/ Kara Zor-El]",
    "Supergirl": "Supergirl [Kara Danvers/ Kara Zor-El]",
    "Superman (Earth One)": "Superman [Clark Kent/ Kal-El]",
    "Superman (Earth-1)": "Superman [Clark Kent/ Kal-El]",
    "Superman (Earth-2)": "Superman [Clark Kent/ Kal-El]",
    "Superman (of Earth-1)": "Superman [Clark Kent/ Kal-El]",
    "Superman (of Earth-2)": "Superman [Clark Kent/ Kal-El]",
    "Superman [Clark Kent] (Earth-2)": "Superman [Clark Kent/ Kal-El]",
    "Superman [Clark Kent]": "Superman [Clark Kent/ Kal-El]",
    "Superman [Clark Kent/ Kal-L]": "Superman [Clark Kent/ Kal-El]",
    "Superman [Clark Smith]": "Superman [Clark Kent/ Kal-El]",
    "Superman [Kal Kent/ Kal-El]": "Superman [Clark Kent/ Kal-El]",
    "Superman [Kal-El]": "Superman [Clark Kent/ Kal-El]",
    "Superman [Kal-El/ Clark Kent]": "Superman [Clark Kent/ Kal-El]",
    "Superman": "Superman [Clark Kent/ Kal-El]",
    "Susan Storm [Invisible Woman]": "Invisible Woman [Sue Storm Richards]",
    "Susan Storm Richards [Invisible Woman]": "Invisible Woman [Sue Storm Richards]",
    "Swamp Thing": "Swamp Thing [Alec Holland]",
    "Sylvester Pussycat": "Sylvester",
    "Sylvester the Cat": "Sylvester",
    "Talia Al Ghul": "Talia al Ghul",
    "Talon [Alton Carver]": "Talon [Calvin Rose]",
    "Talon [Felix Harmon]": "Talon [Calvin Rose]",
    "Talon [Mary Turner]": "Talon [Calvin Rose]",
    "Talon [Mary]": "Talon [Calvin Rose]",
    "Talon [William Cobb]": "Talon [Calvin Rose]",
    "Talon": "Talon [Calvin Rose]",
    "Talons": "Talon [Calvin Rose]",
    "Tarantula": "Tarantula [Catalina Flores]",
    "Tazmanian Devil": "Tasmanian Devil",
    "Tempest": "Tempest [Garth]",
    "Terra [Tara]": "Terra [Tara Markov]",
    "Terra": "Terra [Tara Markov]",
    "The Abomination": "Abomination [Emil Blonski]",
    "the Abomination": "Abomination [Emil Blonski]",
    "The Absorbing Man [Crusher Creel]": "Absorbing Man [Crusher Creel]",
    "the Absorbing Man": "Absorbing Man [Crusher Creel]",
    "The Absorbing Man": "Absorbing Man [Crusher Creel]",
    "The Angel [Warren Worthington III]": "Angel [Warren Worthington III]",
    "The Angel": "Angel [Warren Worthington III]",
    "The Atom [Ray Palmer]": "Atom [Ray Palmer]",
    "the Atom": "Atom [Ray Palmer]",
    "The Atom": "Atom [Ray Palmer]",
    "the Beast": "Beast [Hank McCoy]",
    "The Beast": "Beast [Hank McCoy]",
    "the Beetle [Abner Jenkins]": "Beetle [Abner Jenkins]",
    "the Black Knight [Dane Whitman]": "Black Knight [Dane Whitman]",
    "the Black Knight": "Black Knight [Dane Whitman]",
    "The Black Knight": "Black Knight [Dane Whitman]",
    "the Black Panther": "Black Panther [T'Challa]",
    "The Black Panther": "Black Panther [T'Challa]",
    "the Black Widow [Natasha Romanoff]": "Black Widow [Natasha Romanov]",
    "the Black Widow [Natasha Romanova]": "Black Widow [Natasha Romanov]",
    "The Blob": "Blob [Fred J. Dukes]",
    "The Bronze Tiger [Ben Turner]": "Bronze Tiger [Ben Turner]",
    "The Catwoman [Selina Kyle]": "Catwoman [Selina Kyle]",
    "The Changeling": "Changeling [Garfield Logan]",
    "The Chief [Niles Caulder/ also as the Galactic Guardian]": "The Chief [Niles Caulder]",
    "The Chief": "The Chief [Niles Caulder]",
    "the Chief": "The Chief [Niles Caulder]",
    "The Colossus": "Colossus [Piotr Rasputin]",
    "The Comet": "Comet [Adam Blake]",
    "the Comet": "Comet [Adam Blake]",
    "The Demon [Etrigan]": "Demon [Etrigan/ Jason Blood]",
    "The Demon [Etrigan/ Jason Blood]": "Demon [Etrigan/ Jason Blood]",
    "The Demon Etrigan [Jason Blood]": "Demon [Etrigan/ Jason Blood]",
    "The Demon Etrigan": "Demon [Etrigan/ Jason Blood]",
    "the Destroyer": "Destroyer [Alex Power]",
    "The Destroyer": "Destroyer [Alex Power]",
    "the Doctor": "The Doctor",
    "The Duck Avenger [Donald Duck]": "Donald Duck [The Duck Avenger]",
    "The Enchantress": "Enchantress [June Moone]",
    "the Enchantress": "Enchantress [June Moone]",
    "the Falcon": "Falcon [Sam Wilson]",
    "The Flash [Barry Allen]": "Flash [Barry Allen]",
    "The Flash [Jay Garrick]": "Flash [Jay Garrick]",
    "The Flash [Wally West]": "Flash [Wally West]",
    "The Flash": "Flash [Barry Allen]",
    "The Green Arrow": "Green Arrow [Oliver Queen]",
    "The Green Goblin [Dr. Barton Hamilton]": "Green Goblin [Norman Osborn]",
    "The Green Goblin [Harry Osborn]": "Green Goblin [Norman Osborn]",
    "the Green Goblin [Harry Osborn]": "Green Goblin [Norman Osborn]",
    "The Green Goblin [Norman Osborn]": "Green Goblin [Norman Osborn]",
    "The Green Lantern [Alan Scott]": "Green Lantern [Alan Scott]",
    "The Hawkman [Carter Hall]": "Hawkman [Katar Hol/ Carter Hall]",
    "The Hulk [Bruce Banner]": "Hulk [Bruce Banner]",
    "the Hulk [Bruce Banner]": "Hulk [Bruce Banner]",
    "the Hulk": "Hulk [Bruce Banner]",
    "The Hulk": "Hulk [Bruce Banner]",
    "the Human Bomb [Roy Lincoln]": "Human Bomb [Dave Mathis]",
    "The Human Bomb [Roy Lincoln]": "Human Bomb [Dave Mathis]",
    "The Human Bomb": "Human Bomb [Dave Mathis]",
    "The Human Torch [Jim Hammond]": "Human Torch [Johnny Storm]",
    "the Human Torch [Johnny Storm]": "Human Torch [Johnny Storm]",
    "The Human Torch [Johnny Storm]": "Human Torch [Johnny Storm]",
    "the Human Torch": "Human Torch [Johnny Storm]",
    "The Human Torch": "Human Torch [Johnny Storm]",
    "The Huntress [Helena Wayne]": "Huntress [Helena Wayne]",
    "The Huntress": "Huntress [Helena Bertinelli]",
    "The Invisible Girl [Sue Storm]": "Invisible Woman [Sue Storm Richards]",
    "the Invisible Girl [Sue Storm]": "Invisible Woman [Sue Storm Richards]",
    "The Invisible Girl [Susan Storm]": "Invisible Woman [Sue Storm Richards]",
    "The Invisible Girl": "Invisible Woman [Sue Storm Richards]",
    "the Invisible Girl": "Invisible Woman [Sue Storm Richards]",
    "the Invisible Woman": "Invisible Woman [Sue Storm Richards]",
    "The Joker": "Joker",
    "the Joker": "Joker",
    "the Juggernaut": "Juggernaut [Cain Marko]",
    "The Keeper [Silver Surfer]": "Silver Surfer [Norrin Radd]",
    "The Lizard": "Lizard [Curt Connors]",
    "the Lizard": "Lizard [Curt Connors]",
    "the Man-Thing": "Man-Thing",
    "the Mandarin": "Mandarin",
    "The Mandarin": "Mandarin",
    "The Midnighter": "Midnighter [Lucas Trent]",
    "The Penguin [Oswald Cobblepot]": "Penguin [Oswald Cobblepot]",
    "The Penguin": "Penguin [Oswald Cobblepot]",
    "The Pink Panther": "Pink Panther",
    "The Punisher [Frank Castle]": "Punisher [Frank Castle]",
    "The Punisher 2099 ": "Punisher 2099 [Jake Gallows]",
    "The Punisher": "Punisher [Frank Castle]",
    "the Punisher": "Punisher [Frank Castle]",
    "The Question": "The Question [Vic Sage]",
    "the Question": "The Question [Vic Sage]",
    "The Ray [Happy Terrill]": "The Ray [Ray Terrill]",
    "The Ray": "The Ray [Ray Terrill]",
    "the Red Skull": "Red Skull [Johann Schmidt]",
    "the Rhino": "Rhino [Aleksei Mikhailovich Sytsevich]",
    "The Rhino": "Rhino [Aleksei Mikhailovich Sytsevich]",
    "The Riddler [Edward Nigma]": "Riddler [Edward Nigma]",
    "The Riddler": "Riddler [Edward Nigma]",
    "The Sandman [Wesley Dodds]": "Sandman [Wes Dodds]",
    "The Scarecrow [Jonathan Crane]": "Scarecrow [Jonathan Crane]",
    "the Scarlet Witch [Wanda Maximoff]": "Scarlet Witch [Wanda Maximoff]",
    "the Scarlet Witch": "Scarlet Witch [Wanda Maximoff]",
    "The Scarlet Witch": "Scarlet Witch [Wanda Maximoff]",
    "The Shield [Joe Higgins]": "Shield [Joe Higgins]",
    "The Shield [Lt. Joe Higgins]": "Shield [Joe Higgins]",
    "The Shield": "Shield [Joe Higgins]",
    "The Shocker": "Shocker [Herman Schultz]",
    "the Silver Surfer": "Silver Surfer [Norrin Radd]",
    "The Silver Surfer": "Silver Surfer [Norrin Radd]",
    "The Spectre [Jim Corrigan]": "Spectre [Jim Corrigan]",
    "The Spectre": "Spectre [Jim Corrigan]",
    "The Sub-Mariner [Prince Namor]": "Sub-Mariner [Namor]",
    "the Sub-Mariner [Prince Namor]": "Sub-Mariner [Namor]",
    "The Sub-Mariner": "Sub-Mariner [Namor]",
    "the Sub-Mariner": "Sub-Mariner [Namor]",
    "the Thing [Ben Grimm]": "The Thing [Ben Grimm]",
    "The Thing": "The Thing [Ben Grimm]",
    "the Thing": "The Thing [Ben Grimm]",
    "the Vision": "Vision",
    "The Vision": "Vision",
    "The Vixen": "Vixen [Mari McCabe]",
    "The Vulture": "Vulture [Adrian Toomes]",
    "the Warlord [Travis Morgan]": "Warlord [Travis Morgan]",
    "The Wasp [Janet Van Dyne]": "Wasp [Janet Van Dyne]",
    "the Wasp": "Wasp [Janet Van Dyne]",
    "The Wasp": "Wasp [Janet Van Dyne]",
    "The Wizard [Bentley Wittman]": "Wizard [Bentley Wittman]",
    "Thing [Ben Grim]": "The Thing [Ben Grimm]",
    "Thing [Ben Grimm]": "The Thing [Ben Grimm]",
    "Thing [Benjamin Grimm]": "The Thing [Ben Grimm]",
    "Thing": "The Thing [Ben Grimm]",
    "Thor [Doctor Donald Blake]": "Thor [Thor Odinson/ Donald Blake]",
    "Thor [Don Blake]": "Thor [Thor Odinson/ Donald Blake]",
    "Thor [Donald Blake]": "Thor [Thor Odinson/ Donald Blake]",
    "Thor [Dr. Don Blake]": "Thor [Thor Odinson/ Donald Blake]",
    "Thor [Dr. Donald Blake]": "Thor [Thor Odinson/ Donald Blake]",
    "Thor [Odinson]": "Thor [Thor Odinson/ Donald Blake]",
    "Thor [Thor Odinson]": "Thor [Thor Odinson/ Donald Blake]",
    "Thor Odinson": "Thor [Thor Odinson/ Donald Blake]",
    "Thor": "Thor [Thor Odinson/ Donald Blake]",
    "Throg (The Frog of Thunder)": "Throg",
    "Thunderbird [Neal Shaara]": "Thunderbird [Neal Sharra]",
    "Thunderbird": "Thunderbird [John Proudstar]",
    "Thunderbolt Ross": "General Thunderbolt Ross",
    "Thunderbolt": "Thunderbolt [Jonni Thunder]",
    "Thunderstrike [Kevin Masterson]": "Thunderstrike [Eric Masterson]",
    "Thunderstrike [Kevin Masterson]": "Thunderstrike [Eric Masterson]",
    "Thunderstrike": "Thunderstrike [Eric Masterson]",
    "Tigra": "Tigra [Greer Nelson]",
    "Timber Wolf": "Timber Wolf [Brin Londo]",
    "Titania": "Titania [Davida DeVito]",
    "Toni Ho [Iron Patriot]": "Iron Patriot [Norman Osborn]",
    "Tony Stark [Iron Man]": "Iron Man [Tony Stark]",
    "Tony Stark": "Iron Man [Tony Stark]",
    "Toro [Raymond Thomas]": "Toro [Tom Raymond]",
    "Toro [Thomas Raymond]": "Toro [Tom Raymond]",
    "Toro": "Toro [Tom Raymond]",
    "Turok [Joshua Fireseed]": "Turok [Josh Fireseed]",
    "Turok": "Turok [Josh Fireseed]",
    "Two-Face [Harvey Kent]": "Two-Face [Harvey Dent]",
    "Two-Face": "Two-Face [Harvey Dent]",
    "Ultimate Falcon [Sam Wilson]": "Falcon [Sam Wilson]",
    "Ultimate Hulk": "Hulk [Bruce Banner]",
    "Ultimate Invisible Woman": "Invisible Woman [Sue Storm Richards]",
    "Ultimate Spider-Man [Miles Morales]": "Spider-Man [Miles Morales]",
    "Ultra Boy": "Ultra Boy [Jo Nah]",
    "Ultraman (Earth-3)": "Ultraman",
    "Ultraman [Clark Kent] (Earth-3)": "Ultraman",
    "Ultraman [Clark] (Earth-3)": "Ultraman",
    "Uncle Scrooge McDuck": "Uncle Scrooge",
    "Uncle Scrooge": "Scrooge McDuck",
    "Union Jack [James Montgomery Falsworth]": "Union Jack [Brian Falsworth]",
    "Union Jack": "Union Jack [Brian Falsworth]",
    "Valkyrie [Brunnhilda]": "Valkyrie [Brunnhilde]",
    "Valkyrie": "Valkyrie [Barbara Norris]",
    "Vance Astro": "Major Victory [Vance Astro]",
    "Vandal Savage": "Vandal Savage [Jon Savage]",
    "Venom [Eddie Bock]": "Venom [Eddie Brock]",
    "Venom [Norman Osborn II]": "Venom [Eddie Brock]",
    "Venom": "Venom [Eddie Brock]",
    "Venom": "Venom [Eddie Brock]",
    "Vibe": "Vibe [Cisco Ramon]",
    "Victor Creed [Sabretooth]": "Sabretooth [Victor Creed]",
    "Victor Von Doom [Doctor Doom]": "Doctor Doom [Victor von Doom]",
    "Victor von Doom": "Doctor Doom [Victor von Doom]",
    "Vigilante [Dave Winston]": "Vigilante [Adrian Chase]",
    "Vigilante [Dorian Chase]": "Vigilante [Adrian Chase]",
    "Vigilante [Greg Sanders]": "Vigilante [Adrian Chase]",
    "Vigilante [Patricia Trayce]": "Vigilante [Adrian Chase]",
    "Vigilante": "Vigilante [Adrian Chase]",
    "Vixen [Mari Jiwe McCabe]": "Vixen [Mari McCabe]",
    "Vixen": "Vixen [Mari McCabe]",
    "Vulture [Blackie Drago]": "Vulture [Adrian Toomes]",
    "Vulture": "Vulture [Adrian Toomes]",
    "Wally West [Kid Flash]": "Kid Flash [Wally West]",
    "War Machine [Jim Rhodes]": "War Machine [James Rhodes]",
    "War Machine": "War Machine [James Rhodes]",
    "Warlord": "Warlord [Travis Morgan]",
    "Warpath": "Warpath [James Proudstar]",
    "Warren Worthington III [Angel]": "Angel [Warren Worthington III]",
    "Wasp [Henry Pym]": "Wasp [Hank Pym]",
    "Wasp [Janet Pym]": "Wasp [Janet Van Dyne]",
    "Wasp [Janet Van Dyne-Pym]": "Wasp [Janet Van Dyne]",
    "Wasp [Janet van Dyne]": "Wasp [Janet Van Dyne]",
    "Wasp [Nadia Van Dyne]": "Wasp [Nadia Pym]",
    "Wasp": "Wasp [Janet Van Dyne]",
    "Wasp": "Wasp [Janet Van Dyne]",
    "Weather Wizard [Marco Mardon]": "Weather Wizard [Mark Mardon]",
    "Weather Wizard": "Weather Wizard [Mark Mardon]",
    "Werewolf by Night [Jack Russell]": "Werewolf [Jack Russell]",
    "Werewolf by Night": "Werewolf [Jack Russell]",
    "Werewolf": "Werewolf [Jack Russell]",
    "White Queen [Emma Frost]": "Emma Frost [White Queen]",
    "White Queen": "Emma Frost [White Queen]",
    "Wildcat": "Wildcat [Ted Grant]",
    "Wildfire": "Wildfire [Drake Burroughs]",
    "Wilson Fisk [Kingpin]": "Kingpin [Wilson Fisk]",
    "Winter Soldier [Bucky Barnes]": "Winter Soldier [James Buchanan Barnes]",
    "Winter Soldier [James Buchanan 'Bucky' Barnes]": "Winter Soldier [Bucky Barnes]",
    "Winter Soldier": "Winter Soldier [James Buchanan Barnes]",
    "Wizard": "Wizard [Bentley Wittman]",
    "Wofsbane [Rahne]": "Wolfsbane [Rahne]",
    "Wolfsbane [Rahne]": "Wolfsbane [Rahne Sinclair]",
    "Wolfsbane": "Wolfsbane [Rahne Sinclair]",
    "Wolverine [James Howlett]": "Wolverine [Logan/ James Howlett]",
    "Wolverine [James Howlett/ Logan]": "Wolverine [Logan/ James Howlett]",
    "Wolverine [Laura Kinney]": "Wolverine [X-23/ Laura Kinney]",
    "Wolverine [Laura Kinney/ X-23]": "Wolverine [X-23/ Laura Kinney]",
    "Wolverine [Logan, James Howlett]": "Wolverine [Logan/ James Howlett]",
    "Wolverine [Logan]": "Wolverine [Logan/ James Howlett]",
    "Wolverine [Old Man Logan]": "Old Man Logan [James Howlett]",
    "Wolverine": "Wolverine [Logan/ James Howlett]",
    "Wonder Girl [Cassandra Sandsmark]": "Wonder Girl [Cassie Sandsmark]",
    "Wonder Girl [Cassie Sandmark]": "Wonder Girl [Cassie Sandsmark]",
    "Wonder Girl": "Wonder Girl [Donna Troy]",
    "Wonder Man": "Wonder Man [Simon Williams]",
    "Wonder Woman (Earth-1)": "Wonder Woman [Diana Prince]",
    "Wonder Woman (Earth-2)": "Wonder Woman [Diana Prince]",
    "Wonder Woman (of Earth-1)": "Wonder Woman [Diana Prince]",
    "Wonder Woman (of Earth-2)": "Wonder Woman [Diana Prince]",
    "Wonder Woman [Diana of Themyscira]": "Wonder Woman [Diana Prince]",
    "Wonder Woman [Diana Prince Trevor]": "Wonder Woman [Diana Prince]",
    "Wonder Woman [Diana Prince] (Earth-2)": "Wonder Woman [Diana Prince]",
    "Wonder Woman [Diana]": "Wonder Woman [Diana Prince]",
    "Wonder Woman [Princess Diana]": "Wonder Woman [Diana Prince]",
    "Wonder Woman": "Wonder Woman [Diana Prince]",
    "Wonder-Woman": "Wonder Woman [Diana Prince]",
    "Wylde": "Wylde [Charlie Wylde]",
    "X-23 [Laura Kinney]": "Wolverine [X-23/ Laura Kinney]",
    "X-23": "Wolverine [X-23/ Laura Kinney]",
    "X-Man [Nathan Grey]": "X-Man [Nate Grey]",
    "X-Man": "X-Man [Nate Grey]",
    "X-O Manowar [Aric]": "X-O Manowar [Aric Dacia]",
    "X-O Manowar": "X-O Manowar [Aric Dacia]",
    "Yellowjacket [Henry Pym]": "Yellowjacket [Hank Pym]",
    "Yellowjacket": "Yellowjacket [Hank Pym]",
    "Yondu Udonta": "Yondu",
    "Zatanna Zatara": "Zatanna [Zatanna Zatara]",
    "Zatanna": "Zatanna [Zatanna Zatara]",
}
