class URLs:
    archies = "https://comics-net.s3-us-west-1.amazonaws.com/archies"
    avengers = "https://comics-net.s3-us-west-1.amazonaws.com/avengers"
    defenders = "https://comics-net.s3-us-west-1.amazonaws.com/defenders"
    doom_patrol = "https://comics-net.s3-us-west-1.amazonaws.com/doom_patrol"
    era = "https://comics-net.s3-us-west-1.amazonaws.com/era"
    fantastic_four = "https://comics-net.s3-us-west-1.amazonaws.com/fantastic_four"
    guardians_of_the_galaxy = "https://comics-net.s3-us-west-1.amazonaws.com/guardians_of_the_galaxy"
    inhumans = "https://comics-net.s3-us-west-1.amazonaws.com/inhumans"
    justice_league = "https://comics-net.s3-us-west-1.amazonaws.com/justice_league"
    justice_society_of_america = "https://comics-net.s3-us-west-1.amazonaws.com/justice_society_of_america"
    lantern_corps = "https://comics-net.s3-us-west-1.amazonaws.com/lantern_corps"
    legion_of_super_heroes = "https://comics-net.s3-us-west-1.amazonaws.com/legion_of_super-heroes"
    new_gods = "https://comics-net.s3-us-west-1.amazonaws.com/new_gods"
    spider_man = "https://comics-net.s3-us-west-1.amazonaws.com/spider-man"
    suicide_squad = "https://comics-net.s3-us-west-1.amazonaws.com/suicide_squad"
    teen_titans = "https://comics-net.s3-us-west-1.amazonaws.com/teen_titans"
    x_men = "https://comics-net.s3-us-west-1.amazonaws.com/x-men"